import { existsSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const source = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')

describe('generic shell Toast ownership', () => {
  it('renders one direct Toaster with the original parameters and Motion behavior', () => {
    const appSource = source('./App.tsx')
    const bootstrapShellSource = source('./BootstrapShell.tsx')
    const appMainSource = source('./views/app-main/index.tsx')
    const styles = source('../../assets/styles/tailwind.css')
    const panelStart = bootstrapShellSource.indexOf('<AppMain>')
    const panelEnd = bootstrapShellSource.indexOf('</AppMain>')
    const application = bootstrapShellSource.indexOf('{application ??')
    const toaster = bootstrapShellSource.indexOf('<Toaster')

    expect(panelStart).toBeGreaterThan(-1)
    expect(panelEnd).toBeGreaterThan(panelStart)
    expect(application).toBeGreaterThan(panelStart)
    expect(application).toBeLessThan(panelEnd)
    expect(toaster).toBeGreaterThan(panelEnd)
    expect(bootstrapShellSource.match(/<Toaster\b/g)).toHaveLength(1)
    expect(appSource).not.toMatch(/<Toaster\b|from 'sonner'|useToastPresentation/)
    expect(bootstrapShellSource).toContain("import { Toaster } from 'sonner'")
    expect(bootstrapShellSource).toContain('useToastPresentation()')
    expect(bootstrapShellSource).toContain('richColors')
    expect(bootstrapShellSource).toContain('theme={themeMode}')
    expect(bootstrapShellSource).toContain('offset="70px"')
    expect(bootstrapShellSource).toContain('visibleToasts={1}')
    expect(bootstrapShellSource).toContain('position="top-center"')
    expect(bootstrapShellSource).toContain("toast: 'dark:bg-slate-950 border dark:border-slate-600'")
    expect(appMainSource).toContain("initial={{ opacity: 0, y: 10, x: isOnRightSide ? '-100%' : '0' }}")
    expect(appMainSource).toContain("animate={{ opacity: 1, y: 0, x: isOnRightSide ? '-100%' : '0' }}")
    expect(appMainSource).not.toContain('transformTemplate')
    expect(styles).not.toMatch(/webchat-(?:panel|launcher|reconnect)-toaster|data-webchat-interactive/)
  })

  it('keeps Runtime readiness unique while bootstrap publishes generic shell feedback', () => {
    const appSource = source('./App.tsx')
    const entrySource = source('./index.tsx')
    const bootstrapSource = source('./Bootstrap.tsx')
    const bootstrapShellSource = source('./BootstrapShell.tsx')
    const readinessSource = source('../../domain/Readiness.ts')

    expect(appSource).not.toMatch(/runtimeHostPhase|ReadinessDomain|WebChat connecting|WebChat unavailable|<output/)
    expect(appSource).not.toMatch(/AlertCircleIcon|LoaderCircleIcon/)
    expect(entrySource).not.toMatch(/runtime-unavailable|WebChat unavailable|location\.reload/)
    expect(`${bootstrapSource}\n${bootstrapShellSource}`).not.toMatch(/ReadinessDomain|ToastDomain|location\.reload/)
    expect(bootstrapSource).toContain('toastPresentationDomain.command.PublishCommand')
    expect(bootstrapSource).toContain("id: 'webchat-bootstrap'")
    expect(bootstrapSource).toContain("message: 'WebChat unavailable'")
    expect(bootstrapShellSource).toContain('<output aria-live="polite">')
    expect(bootstrapShellSource).toContain('Preparing WebChat')
    expect(bootstrapShellSource).not.toMatch(/role=.*alert|AlertCircleIcon|WebChat unavailable|Retry WebChat setup/)
    expect(bootstrapShellSource).toContain('<AppButton')
    expect(bootstrapShellSource).toContain('onBootstrapRetry={onRetry}')
    expect(readinessSource).toContain("default: 'connecting'")
    expect(readinessSource).toContain('StateChangedEvent')
  })

  it('deletes reconnect presentation residue and isolates the generic adapter from business sources', () => {
    const presenterSource = source('./components/toast-presentation.tsx')
    const feedbackSource = source('../../domain/AppFeedback.ts')
    const toastSource = source('../../domain/Toast.ts')

    expect(existsSync(new URL('./components/reconnect-toast.tsx', import.meta.url))).toBe(false)
    expect(existsSync(new URL('./components/reconnect-toast.test.ts', import.meta.url))).toBe(false)
    expect(presenterSource).not.toMatch(/ChatRoom|Readiness|Runtime|Network|AppStatus|panel|reconnect/i)
    expect(presenterSource).toContain("from '@/domain/ToastPresentation'")
    expect(feedbackSource).toContain("from '@/domain/ChatRoom'")
    expect(feedbackSource).toContain("from '@/domain/Readiness'")
    expect(feedbackSource).toContain("from '@/domain/ToastPresentation'")
    expect(feedbackSource).toContain('minimumVisibleMs: 300')
    expect(toastSource).not.toMatch(/Descriptor|Presentation|SurfaceMounted|Acknowledge/)
  })
})
