allowBuilds:
  bufferutil: true
  core-js: false
  esbuild: true
  spawn-sync: true
  utf-8-validate: true
  wxt: true
patchedDependencies:
  '@shadcn/react@0.3.0': patches/@shadcn__react@0.3.0.patch
