export enum EVENT {
  OPTIONS_PAGE_OPEN = `WEB_CHAT_OPTIONS_PAGE_OPEN`,
  APP_OPEN = 'WEB_CHAT_APP_OPEN',
  NOTIFICATION_PUSH = 'WEB_CHAT_NOTIFICATION_PUSH',
  NOTIFICATION_CLEAR = 'WEB_CHAT_NOTIFICATION_CLEAR'
}
