const generateRandomName = (): string => {
  const firstNames = [
    'Alex',
    'Blake',
    'Casey',
    'Dana',
    'Eden',
    'Frankie',
    'Gray',
    'Harper',
    'Indigo',
    'Jordan',
    'Kennedy',
    'Logan',
    'Morgan',
    'Noah',
    'Parker',
    'Quinn',
    'Riley',
    'Sage',
    'Taylor',
    'Avery',
    'Bella',
    'Charlie',
    'Daisy',
    'Ella',
    'Fiona',
    'Grace',
    'Hannah',
    'Ivy',
    'Jasmine',
    'Katherine',
    'Luna',
    'Mia',
    'Nina',
    'Olivia',
    'Penelope',
    'Quinn',
    'Riley',
    'Sage',
    'Taylor',
    'Avery',
    'Bella',
    'Charlie',
    'Daisy',
    'Ella',
    'JinPing'
  ]

  const lastNames = [
    'Smith',
    'Johnson',
    'Williams',
    'Brown',
    'Jones',
    'Garcia',
    'Miller',
    'Davis',
    'Rodriguez',
    'Martinez',
    'Hernandez',
    'Lopez',
    'Gonzalez',
    'Wilson',
    'Anderson',
    'Thomas',
    'Taylor',
    'Moore',
    'Jackson',
    'Martin',
    'Nguyen',
    'Ochoa',
    'Perez',
    'Quintero',
    'Rivera',
    'Santos',
    'Torres',
    'Vargas',
    'Wright',
    'Xiong',
    'Yang',
    'Zhao',
    'Zhang',
    'Li',
    'Wang',
    'Chen',
    'Liu',
    'Yang',
    'Zhou',
    'Wu',
    'Lin',
    'Lu',
    'Zheng',
    'Huang',
    'Xi'
  ]

  const randomFirstName = firstNames[Math.floor(Math.random() * firstNames.length)]
  const randomLastName = lastNames[Math.floor(Math.random() * lastNames.length)]

  return `${randomFirstName} ${randomLastName}`
}

export default generateRandomName
